name: Terraform Format, Validate, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.3

    - name: Terraform Init
      env:
        MGC_OBJ_KEY_SECRET: ${{ secrets.MGC_OBJ_KEY_SECRET }}
        MGC_OBJ_KEY_ID: ${{ secrets.MGC_OBJ_KEY_ID }}
        MGC_REGION: ${{ secrets.MGC_REGION }}
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check -recursive -diff

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Test
      run: terraform test