name: Terraform Format, Validate, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install mgc-cli
      run: |
        wget https://github.com/MagaluCloud/mgccli/releases/download/v0.28.4/mgccli_0.28.4_linux_amd64.deb
        sudo dpkg -i mgccli_0.28.4_linux_amd64.deb

    - name: Export environment variables
      run: |
        export MGC_API_KEY=${{ secrets.MGC_API_KEY }}
        export MGC_OBJ_KEY_ID=${{ secrets.MGC_OBJ_KEY_ID }}
        export MGC_OBJ_KEY_SECRET=${{ secrets.MGC_OBJ_KEY_SECRET }}
        export MGC_REGION=${{ secrets.MGC_REGION }}


    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.3

    - name: Terraform Init
      env:
        MGC_OBJ_KEY_SECRET: ${{ secrets.MGC_OBJ_KEY_SECRET }}
        MGC_OBJ_KEY_ID: ${{ secrets.MGC_OBJ_KEY_ID }}
        MGC_REGION: ${{ secrets.MGC_REGION }}
        MGC_API_KEY: ${{ secrets.MGC_API_KEY }}
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check -recursive -diff

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Test
      run: terraform test